default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEV", "todolist_development") %>
  username: <%= ENV.fetch("DB_USER_DEV", "todolist") %>
  password: <%= ENV.fetch("DB_PASSWORD_DEV", 12345) %>
  host: <%= ENV.fetch("DB_HOST_DEV", "localhost") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "todolist_test") %>
  username: <%= ENV.fetch("DB_USER_TEST", "todolist") %>
  password: <%= ENV.fetch("DB_PASSWORD_TEST", 12345) %>
  host: <%= ENV.fetch("DB_HOST_TEST", "localhost") %>

production:
  <<: *default
  database: <%= ENV["DB_NAME_PROD"] || "fallback_prod_db" %>
  username: <%= ENV["DB_USERNAME_PROD"] || "fallback_user" %>
  password: <%= ENV["DB_PASSWORD_PROD"] || "fallback_pass" %>
  host: <%= ENV["DB_HOST_PROD"] || "localhost" %>
